// AUTO-GENERATED by scripts/scrape-brand-logos.ts --finalize. Do not edit by hand.
// Maps a product_brand slug to its logo dimensions; the asset is
// public/brand-logos/<slug>.webp. Presence here = approved for display.
export const BRAND_LOGOS: Record<string, { w: number; h: number }> = {
};
