<?php
/**
 * Plugin Name: Male Q — Restricted Products Guard
 * Description: Stops Stripe-restricted products (CBD/THC, vapes, paraphernalia, poppers,
 * drug-test evasion, enhancement pills) from being published through WordPress: wp-admin,
 * the WooCommerce CSV importer, the REST API and wp-cli all pass through wp_insert_post_data,
 * so this is the backstop behind the Node-side import gate (lib/import/restricted-products.ts).
 * Version: 1.0
 *
 * Two checks run whenever a `product` is saved with post_status=publish:
 *   1. Products carrying `_maleq_hidden_reason` postmeta (set by the restricted-products audit
 *      / the 2026-09-11 Stripe CBD purge) are forced back to draft. Delete that meta first if a
 *      product was hidden by mistake — that is the deliberate "I know what I'm doing" step.
 *   2. Title, description, excerpt, brand and category names are run through the same rule
 *      set the importers use. The rules live in `maleq-restricted-rules.json` next to this file,
 *      GENERATED by `bun scripts/gen-restricted-rules.ts` — never edit the JSON by hand; edit
 *      lib/import/restricted-products.ts (or data/restricted-allowlist.json for false
 *      positives), regenerate, and deploy both files.
 *
 * A blocked publish lands as draft with an admin notice (wp-admin), a WP_CLI warning (cli) and
 * an error_log line, and the reason is stored in `_maleq_restricted_block` postmeta so the edit
 * screen keeps showing it. Set `define('MALEQ_RESTRICTED_GUARD_DISABLED', true)` in wp-config
 * to switch the guard off temporarily (e.g. a deliberate, backed-up bulk restore).
 */

if (!defined('ABSPATH')) {
    exit;
}

const MALEQ_RPG_RULES_FILE   = __DIR__ . '/maleq-restricted-rules.json';
const MALEQ_RPG_BLOCK_META   = '_maleq_restricted_block';
const MALEQ_RPG_NOTICE_KEY   = 'maleq_rpg_notices_';

/** Load + cache the generated rule set. Returns null (guard off, logged once) if unreadable. */
function maleq_rpg_config(): ?array
{
    static $cfg = false;
    if ($cfg !== false) {
        return $cfg;
    }
    $cfg = null;
    if (!is_readable(MALEQ_RPG_RULES_FILE)) {
        error_log('[maleq-restricted-guard] rules file missing: ' . MALEQ_RPG_RULES_FILE . ' — guard inactive');
        return null;
    }
    $decoded = json_decode((string) file_get_contents(MALEQ_RPG_RULES_FILE), true);
    if (!is_array($decoded) || empty($decoded['rules'])) {
        error_log('[maleq-restricted-guard] rules file invalid — guard inactive');
        return null;
    }
    $cfg = $decoded;
    return $cfg;
}

/** JS regex {source, flags} → PCRE. `g` has no PCRE equivalent (preg_replace is global). */
function maleq_rpg_re(array $r): string
{
    $flags = str_replace(['g', 'y'], '', (string) ($r['flags'] ?? ''));
    return '~' . str_replace('~', '\~', (string) $r['source']) . '~' . $flags;
}

function maleq_rpg_match(array $r, string $text): ?string
{
    $ok = @preg_match(maleq_rpg_re($r), $text, $m);
    if ($ok === false) {
        error_log('[maleq-restricted-guard] bad pattern: ' . $r['source'] . ' (' . preg_last_error_msg() . ')');
        return null;
    }
    return $ok === 1 ? trim((string) $m[0]) : null;
}

/** Mirror of plainText() in restricted-products.ts. */
function maleq_rpg_plain_text(string $html): string
{
    $t = preg_replace('~<[^>]+>~', ' ', $html);
    $t = preg_replace('~&nbsp;|&#160;~i', ' ', $t);
    $t = preg_replace('~&amp;~i', '&', $t);
    return trim((string) preg_replace('~\s+~', ' ', (string) $t));
}

/** Mirror of stripNegatedClaims(): drop "THC-free", "0% THC", "without any CBD"… */
function maleq_rpg_strip_negated(string $text, array $cfg): string
{
    foreach ($cfg['negatedClaims'] ?? [] as $r) {
        $text = (string) @preg_replace(maleq_rpg_re($r), ' ', $text);
    }
    return $text;
}

/**
 * Mirror of checkRestrictedProduct(). $input keys: name, description, brand, categories[], sku, barcode.
 * Returns null when allowed, otherwise ['category' => …, 'field' => …, 'matches' => [...]].
 */
function maleq_rpg_check(array $input, array $cfg): ?array
{
    $texts = [
        'name'        => [maleq_rpg_strip_negated((string) ($input['name'] ?? ''), $cfg)],
        'brand'       => !empty($input['brand']) ? [(string) $input['brand']] : [],
        'category'    => array_values(array_filter(array_map('strval', $input['categories'] ?? []))),
        'description' => !empty($input['description'])
            ? [maleq_rpg_strip_negated(maleq_rpg_plain_text((string) $input['description']), $cfg)]
            : [],
    ];

    $category = null;
    $field    = null;
    $matches  = [];

    $brandKey = strtolower(trim((string) ($input['brand'] ?? '')));
    if ($brandKey !== '' && isset($cfg['brands'][$brandKey])) {
        $category  = $cfg['brands'][$brandKey];
        $field     = 'brand';
        $matches[] = 'brand:' . trim((string) $input['brand']);
    }

    foreach ($cfg['rules'] as $rule) {
        foreach ($rule['fields'] as $f) {
            foreach ($texts[$f] ?? [] as $text) {
                if ($text === '') {
                    continue;
                }
                $hit = maleq_rpg_match($rule['pattern'], $text);
                if ($hit === null) {
                    continue;
                }
                if (!empty($rule['unless']) && maleq_rpg_match($rule['unless'], $text) !== null) {
                    continue;
                }
                if ($category === null) {
                    $category = $rule['category'];
                    $field    = $f;
                }
                if ($hit !== '' && !in_array($hit, $matches, true)) {
                    $matches[] = $hit;
                }
            }
        }
    }

    if ($category === null) {
        return null;
    }

    // Allowlist (data/restricted-allowlist.json, baked into the JSON): by SKU/barcode or exact title.
    $ids   = array_map('strtolower', $cfg['allowlist']['ids'] ?? []);
    $names = array_map('strtolower', $cfg['allowlist']['names'] ?? []);
    foreach ([$input['sku'] ?? '', $input['barcode'] ?? ''] as $id) {
        $id = strtolower(trim((string) $id));
        if ($id !== '' && in_array($id, $ids, true)) {
            return null;
        }
    }
    if (in_array(strtolower(trim((string) ($input['name'] ?? ''))), $names, true)) {
        return null;
    }

    return ['category' => $category, 'field' => $field, 'matches' => $matches];
}

/** Term names for a taxonomy: existing terms on the post + names/ids arriving via tax_input. */
function maleq_rpg_term_names(int $post_id, string $taxonomy, array $postarr): array
{
    $names = [];
    if ($post_id > 0) {
        $terms = wp_get_object_terms($post_id, $taxonomy, ['fields' => 'names']);
        if (!is_wp_error($terms)) {
            $names = $terms;
        }
    }
    $incoming = $postarr['tax_input'][$taxonomy] ?? null;
    if (is_string($incoming)) {
        $incoming = array_map('trim', explode(',', $incoming));
    }
    if (is_array($incoming)) {
        foreach ($incoming as $t) {
            if (is_numeric($t)) {
                $term = get_term((int) $t, $taxonomy);
                if ($term && !is_wp_error($term)) {
                    $names[] = $term->name;
                }
            } elseif (is_string($t) && $t !== '') {
                $names[] = $t;
            }
        }
    }
    return array_values(array_unique($names));
}

function maleq_rpg_meta(int $post_id, string $key, array $postarr): string
{
    if (isset($postarr['meta_input'][$key])) {
        return (string) $postarr['meta_input'][$key];
    }
    return $post_id > 0 ? (string) get_post_meta($post_id, $key, true) : '';
}

/** Why this save must not publish, or null if it may. */
function maleq_rpg_block_reason(int $post_id, array $data, array $postarr): ?string
{
    $cfg = maleq_rpg_config();
    if ($cfg === null) {
        return null;
    }

    $hiddenKey = (string) ($cfg['hiddenReasonMeta'] ?? '_maleq_hidden_reason');
    $hidden    = maleq_rpg_meta($post_id, $hiddenKey, $postarr);
    if ($hidden !== '') {
        return sprintf(
            'hidden by policy (%s = %s). Delete that meta first if this product was hidden by mistake.',
            $hiddenKey,
            $hidden
        );
    }

    $brands = maleq_rpg_term_names($post_id, 'product_brand', $postarr);
    $result = maleq_rpg_check([
        'name'        => (string) ($data['post_title'] ?? ''),
        'description' => (string) ($data['post_content'] ?? '') . "\n" . (string) ($data['post_excerpt'] ?? ''),
        'brand'       => $brands[0] ?? '',
        'categories'  => array_merge(maleq_rpg_term_names($post_id, 'product_cat', $postarr), array_slice($brands, 1)),
        'sku'         => maleq_rpg_meta($post_id, '_sku', $postarr),
        'barcode'     => maleq_rpg_meta($post_id, '_wt_barcode', $postarr) ?: maleq_rpg_meta($post_id, '_stc_upc', $postarr),
    ], $cfg);

    if ($result === null) {
        return null;
    }
    return sprintf(
        'Stripe-restricted (%s via %s: %s). Fix the rule / allowlist in the repo and redeploy maleq-restricted-rules.json if this is a false positive.',
        $result['category'],
        $result['field'],
        implode(', ', array_slice($result['matches'], 0, 4))
    );
}

function maleq_rpg_disabled(): bool
{
    return defined('MALEQ_RESTRICTED_GUARD_DISABLED') && MALEQ_RESTRICTED_GUARD_DISABLED;
}

/** Reason for a new product (ID=0 inside the filter), attached as meta once the row exists. */
function maleq_rpg_pending(?string $set = null, bool $clear = false): ?string
{
    static $pending = null;
    if ($clear) {
        $pending = null;
    } elseif ($set !== null) {
        $pending = $set;
    }
    return $pending;
}

function maleq_rpg_report(int $post_id, string $title, string $reason): void
{
    $msg = sprintf('"%s" (#%d) was NOT published: %s', $title, $post_id, $reason);
    error_log('[maleq-restricted-guard] ' . $msg);
    if ($post_id > 0) {
        update_post_meta($post_id, MALEQ_RPG_BLOCK_META, wp_slash($reason));
    } else {
        maleq_rpg_pending($reason);
    }
    if (defined('WP_CLI') && WP_CLI) {
        \WP_CLI::warning('[restricted-guard] ' . $msg);
    }
    if (function_exists('is_user_logged_in') && is_user_logged_in()) {
        $key       = MALEQ_RPG_NOTICE_KEY . get_current_user_id();
        $notices   = get_transient($key) ?: [];
        $notices[] = $msg;
        set_transient($key, array_slice($notices, -10), 5 * MINUTE_IN_SECONDS);
    }
}

/**
 * Main gate. wp-admin, Quick/Bulk edit, the WooCommerce CSV importer, the WC/WP REST APIs
 * and `wp post update` all reach wp_insert_post() and therefore this filter.
 */
add_filter('wp_insert_post_data', 'maleq_rpg_filter_post_data', 10, 2);
function maleq_rpg_filter_post_data(array $data, array $postarr): array
{
    if (($data['post_type'] ?? '') !== 'product' || ($data['post_status'] ?? '') !== 'publish' || maleq_rpg_disabled()) {
        return $data;
    }

    $post_id = (int) ($postarr['ID'] ?? 0);
    $reason  = maleq_rpg_block_reason($post_id, $data, $postarr);
    if ($reason === null) {
        if ($post_id > 0) {
            delete_post_meta($post_id, MALEQ_RPG_BLOCK_META);
        }
        return $data;
    }

    $data['post_status'] = 'draft';
    maleq_rpg_report($post_id, (string) ($data['post_title'] ?? ''), $reason);
    return $data;
}

add_action('wp_insert_post', 'maleq_rpg_after_insert', 10, 3);
function maleq_rpg_after_insert(int $post_id, $post, bool $update): void
{
    $pending = maleq_rpg_pending();
    if ($pending === null) {
        return;
    }
    maleq_rpg_pending(null, true);
    if (!$update && $post instanceof WP_Post && $post->post_type === 'product') {
        update_post_meta($post_id, MALEQ_RPG_BLOCK_META, wp_slash($pending));
    }
}

/**
 * Backstop for the two publish paths that write post_status with a raw $wpdb->update and
 * skip wp_insert_post_data: WP-Cron publishing a scheduled product (wp_publish_post) and
 * the WooCommerce data store's direct status writes. Reverting through wp_update_post
 * re-enters the filter above, which sees status=draft and lets it through — no loop.
 */
add_action('transition_post_status', 'maleq_rpg_on_transition', 10, 3);
function maleq_rpg_on_transition(string $new_status, string $old_status, $post): void
{
    static $reverting = false;
    if ($reverting || $new_status !== 'publish' || !($post instanceof WP_Post) || $post->post_type !== 'product' || maleq_rpg_disabled()) {
        return;
    }
    $reason = maleq_rpg_block_reason((int) $post->ID, [
        'post_title'   => $post->post_title,
        'post_content' => $post->post_content,
        'post_excerpt' => $post->post_excerpt,
    ], []);
    if ($reason === null) {
        return;
    }
    $reverting = true;
    wp_update_post(['ID' => $post->ID, 'post_status' => 'draft']);
    $reverting = false;
    maleq_rpg_report((int) $post->ID, $post->post_title, $reason);
}

add_action('admin_notices', 'maleq_rpg_admin_notices');
function maleq_rpg_admin_notices(): void
{
    $key     = MALEQ_RPG_NOTICE_KEY . get_current_user_id();
    $notices = get_transient($key);
    if ($notices) {
        delete_transient($key);
        foreach ($notices as $n) {
            printf(
                '<div class="notice notice-error"><p><strong>Restricted products guard:</strong> %s</p></div>',
                esc_html($n)
            );
        }
    }

    // Persistent reminder on the edit screen of a blocked / hidden product.
    $screen = function_exists('get_current_screen') ? get_current_screen() : null;
    if ($screen && $screen->base === 'post' && $screen->post_type === 'product' && !empty($_GET['post'])) {
        $pid    = (int) $_GET['post'];
        $cfg    = maleq_rpg_config();
        $hidden = $cfg ? (string) get_post_meta($pid, (string) ($cfg['hiddenReasonMeta'] ?? '_maleq_hidden_reason'), true) : '';
        $block  = (string) get_post_meta($pid, MALEQ_RPG_BLOCK_META, true);
        if ($hidden !== '') {
            printf(
                '<div class="notice notice-warning"><p><strong>Hidden by policy</strong> (<code>_maleq_hidden_reason=%s</code>). Publishing is blocked until that meta is removed. Stripe reinstated the account on the condition these products stay off the store.</p></div>',
                esc_html($hidden)
            );
        } elseif ($block !== '') {
            printf(
                '<div class="notice notice-warning"><p><strong>Last publish attempt was blocked:</strong> %s</p></div>',
                esc_html($block)
            );
        }
    }
}
