/**
 * Generate lib/products/size-units-data.ts from scripts/size-cleanup-map.generated.json.
 *
 * Emits SIZE_UNITS: a map from canonical pa_size term slug -> native measurement
 * { dim, value, unit }. The storefront metric/imperial toggle (lib/products/size-units.ts)
 * uses this to reformat length & volume size values; slugs absent from the map
 * (apparel, pack counts, review terms) render unchanged.
 *
 * Run AFTER gen-size-map.ts. Re-run whenever the cleanup map changes.
 *
 * Usage: bun run scripts/gen-size-units.ts
 */
import map from './size-cleanup-map.generated.json';
import { writeFileSync } from 'fs';

type Mapping = {
  action: string; target?: string; unit?: { dim: string; value: number; u: string }; axis: string;
};

const mappings = map as Mapping[];
const out = new Map<string, { dim: string; value: number; unit: string }>();
for (const m of mappings) {
  if (!m.unit) continue;
  if (m.action !== 'KEEP' && m.action !== 'MERGE') continue;
  // key by canonical target slug (the slug terms/variations use after migration)
  if (!m.target) continue;
  if (!out.has(m.target)) out.set(m.target, { dim: m.unit.dim, value: m.unit.value, unit: m.unit.u });
}

const entries = [...out.entries()].sort((a, b) => a[0].localeCompare(b[0]));
const lines = entries.map(([slug, u]) => `  ${JSON.stringify(slug)}: { dim: '${u.dim}', value: ${u.value}, unit: '${u.unit}' },`);

const body = `// AUTO-GENERATED by scripts/gen-size-units.ts — do not edit by hand.
// Native measurement for each convertible pa_size term slug (length / volume / weight),
// used by lib/products/size-units.ts to render the metric/imperial toggle.
// Slugs not present here (apparel sizes, pack counts) are not convertible and render as-is.

export type SizeDim = 'length' | 'volume' | 'weight';
export type SizeNativeUnit = 'in' | 'cm' | 'mm' | 'ft' | 'oz' | 'ml' | 'l' | 'g';

export interface SizeUnit {
  dim: SizeDim;
  value: number;
  unit: SizeNativeUnit;
}

export const SIZE_UNITS: Record<string, SizeUnit> = {
${lines.join('\n')}
};
`;

writeFileSync('lib/products/size-units-data.ts', body);
console.log(`Wrote lib/products/size-units-data.ts with ${entries.length} convertible terms.`);
const byDim: Record<string, number> = {};
for (const [, u] of entries) byDim[u.dim] = (byDim[u.dim] || 0) + 1;
console.log('  by dim:', byDim);
