/**
 * gen-brand-websites.ts
 *
 * Reads scripts/brand-websites.json and emits an idempotent SQL transaction
 * that UPSERTs the `maleq_brand_website` termmeta on each matching
 * `product_brand` term. wp_termmeta has no unique key on (term_id, meta_key),
 * so each brand is DELETE-then-INSERT (safe to re-run).
 *
 * Output: scripts/output/brand-websites.generated.sql
 *
 * Run server-side over SSH per the bulk-migration pattern:
 *   DRY-RUN (no writes, prints what would change):
 *     ( echo 'BEGIN;'; cat scripts/output/brand-websites.generated.sql; \
 *       echo 'SELECT t.slug, tm.meta_value FROM wp_termmeta tm JOIN wp_terms t ON t.term_id=tm.term_id WHERE tm.meta_key=\"maleq_brand_website\" ORDER BY t.slug; ROLLBACK;' ) \
 *       | ssh hetzner 'sudo -u maleq-wp -- wp --path=/home/maleq-wp/htdocs/wp.maleq.com db query'
 *   APPLY:
 *     ( echo 'BEGIN;'; cat scripts/output/brand-websites.generated.sql; echo 'COMMIT;' ) \
 *       | ssh hetzner 'sudo -u maleq-wp -- wp --path=/home/maleq-wp/htdocs/wp.maleq.com db query'
 *   then: ssh hetzner 'sudo -u maleq-wp -- wp --path=/home/maleq-wp/htdocs/wp.maleq.com cache flush'
 *
 * (The runtime brand cache has a 5-min TTL, so the frontend picks it up shortly after.)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const META_KEY = 'maleq_brand_website';
const ROOT = join(import.meta.dir ?? __dirname, '..');
const INPUT = join(ROOT, 'scripts/brand-websites.json');
const OUT_DIR = join(ROOT, 'scripts/output');
const OUT_SQL = join(OUT_DIR, 'brand-websites.generated.sql');

interface BrandEntry {
  slug: string;
  name?: string;
  website: string;
  verified?: boolean;
}

function sqlString(value: string): string {
  // mysql single-quote escaping (matches WP-CLI db query / MySQL defaults)
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function isHttpUrl(value: string): boolean {
  return /^https?:\/\/[^\s'"]+$/i.test(value);
}

function main() {
  const raw = JSON.parse(readFileSync(INPUT, 'utf8')) as { brands: BrandEntry[] };
  const brands = raw.brands.filter(b => b.slug && b.website);

  const problems: string[] = [];
  const seen = new Set<string>();
  for (const b of brands) {
    if (seen.has(b.slug)) problems.push(`duplicate slug: ${b.slug}`);
    seen.add(b.slug);
    if (!isHttpUrl(b.website)) problems.push(`bad URL for ${b.slug}: ${b.website}`);
  }
  if (problems.length) {
    console.error('Validation errors:\n  ' + problems.join('\n  '));
    process.exit(1);
  }

  const lines: string[] = [
    `-- Generated by scripts/gen-brand-websites.ts`,
    `-- ${brands.length} brand website(s). Idempotent (DELETE-then-INSERT). Wrap in BEGIN/COMMIT to apply.`,
    ``,
  ];

  for (const b of brands) {
    const slug = sqlString(b.slug);
    const url = sqlString(b.website);
    lines.push(`-- ${b.name ?? b.slug}${b.verified ? '' : '  [UNVERIFIED]'}`);
    lines.push(
      `DELETE tm FROM wp_termmeta tm ` +
        `JOIN wp_terms t ON t.term_id = tm.term_id ` +
        `JOIN wp_term_taxonomy tt ON tt.term_id = t.term_id AND tt.taxonomy = 'product_brand' ` +
        `WHERE tm.meta_key = '${META_KEY}' AND t.slug = ${slug};`
    );
    lines.push(
      `INSERT INTO wp_termmeta (term_id, meta_key, meta_value) ` +
        `SELECT t.term_id, '${META_KEY}', ${url} ` +
        `FROM wp_terms t JOIN wp_term_taxonomy tt ON tt.term_id = t.term_id ` +
        `WHERE tt.taxonomy = 'product_brand' AND t.slug = ${slug};`
    );
    lines.push(``);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_SQL, lines.join('\n'), 'utf8');

  const verified = brands.filter(b => b.verified).length;
  console.log(`Wrote ${OUT_SQL}`);
  console.log(`  ${brands.length} brands (${verified} verified, ${brands.length - verified} unverified)`);
  console.log(`\nDry-run (rolls back, shows resulting rows):`);
  console.log(
    `  ( echo 'BEGIN;'; cat scripts/output/brand-websites.generated.sql; \\\n` +
      `    printf 'SELECT t.slug, tm.meta_value FROM wp_termmeta tm JOIN wp_terms t ON t.term_id=tm.term_id WHERE tm.meta_key=\\"%s\\" ORDER BY t.slug;\\nROLLBACK;\\n' '${META_KEY}' ) \\\n` +
      `    | ssh hetzner 'sudo -u maleq-wp -- wp --path=/home/maleq-wp/htdocs/wp.maleq.com db query'`
  );
}

main();
